data <- read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors = FALSE)
data$DateTime <- strptime(paste(data$Date, data$Time),"%d/%m/%Y %H:%M:%S")
data <- subset(data, DateTime >= strptime("2007-02-01 00:00:00", "%Y-%m-%d %H:%M:%S") & DateTime < strptime("2007-02-03 00:00:00", "%Y-%m-%d %H:%M:%S"))

plot(data$DateTime, data$Sub_metering_1, type="l", xlab = "", ylab = "Energy sub metering")
lines(data$DateTime, data$Sub_metering_2, type="l", col="red")
lines(data$DateTime, data$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty = c(1,1,1))
dev.copy(png, file = "p3.png")
dev.off()